name: CI
on: [push, pull_request, release]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer

jobs:
  check-lexicon:
    name: CheckLexicon
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: UserLexicon SwiftRun
        run: swift run -c release
