name: CI
on: [push, pull_request, release]

# env:
#   DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  checklexicon:
    name: CheckLexicon
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Swift Run
        run: swift run -c release
